apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-5cabz997goxty
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-5cabz997goxty
    app.kubernetes.io/part-of: test-metric-2dse11eg9hk9k
  name: component-5cabz997goxty
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-app
    app.kubernetes.io/instance: component-5cabz997goxty
status:
  loadBalancer: {}
